### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by jduerholt** [basf/mopti#33]
Hi all,

I was looking in the documentation at the very nice `Problem reduction` page. 

Can it be that you have an error in the first example? 

![image](https://user-images.githubusercontent.com/28678090/162163379-bac41efb-11cd-40e0-af1e-ca15dbfbdfc4.png)

For me the bounds for `x3` should be the same before and after the transformation. 

Best,

Johannes

**Comment by DavidWalz** [comment]
Thanks Johannes!
