### ISSUE TITLE
Optional names attribute for nonlinear equalities

### ISSUE THREAD

**Issue by Osburg** [basf/mopti#39]
It happens that one wants to do checks on the names of constraints of a problem (For example when we want to make sure that the constraints do not affect certain inputs). This is easily possible for linear constraints and nchoosek constraints, but not for nonlinear constraints, because nonlinear constraints do not have the `names` attribute. Would you accept a PR that adds an optional `names` attribute for nonlinear constraints? This way the user could provide information which variables are occuring in the nonlinear constraint's `expression`. This would allow for doing checks like the ones I mentioned above for all types of constraints.

**Comment by Osburg** [comment]
To solve constrained optimization tasks with gradient based solvers the jacobians of constraint functions are evaluated. For these situations it would be useful to also have an (optional) `jacobian` attribute for opti constraints.

**Comment by bertiqwerty** [comment]
Hi Aaron, we are focusing on the new open source package [bofire](https://github.com/experimental-design/bofire/). We have also merged the DoE functionality there. Maybe, you want to consider making contributions there instead of in Opti?

**Comment by Osburg** [comment]
Hi Behrang, ok, will keep that in mind. Thanks for letting me know!

**Comment by DavidWalz** [comment]
Both the names attribute and optional gradients are useful. I think it would be a good addition in bofire.
